### ISSUE TITLE
Hashing fixes

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell-backend#22]
1. Why is there WDL hashing code in cromwell-backend?
2. The hashing logic does not consider key names or appear to take types into account properly.

See comments at broadinstitute/cromwell-backend#21

**Comment by francares** [comment]
1. WDL hashing is because cromwell-backend depends on WDL4s since WDL4s is in every place in Cromwell.
   In the future with the implementation of a GenericModel that will go away as the same as other things.
   Now, TaskDescriptor depends on WDL4s and I think the signature belongs to Cromwell-Backend
   but there is an undesired implementation there due to the constraint of "I cannot get rid of WDL4s at this moment "
2. If you take a look to current Cromwell version
   (https://github.com/broadinstitute/cromwell/blob/da379319aef41081fd1c1996512e64db692e501c/src/main/scala/cromwell/engine/Hashing.scala) you will see similar logic but with the difference that in the new implementation it's recursive and solve the issue of ordering in maps.
   The only issue I see that was introduced is the fact of hashes for keys in maps are not calculated. I think it's a corner case with a low chance of happening (P4).

**Comment by mcovarr** [comment]
1. My point here was that hashing should be the concern of the bindings layer and not cromwell-backend.  i.e. WdlValue should support a `hash` method.
2. WDL does not support ordered maps so this change is not fixing a problem.  Furthermore beyond the issues that @cjllanwarne has already pointed out, we may already have call caching in production by the time these changes are merged at which point even a correct but arbitrary change to the hash algorithm would cause cache misses and incur unnecessary compute costs.

**Comment by francares** [comment]
1. Yes, but what I'm saying is we don't need that since in the future the hashes will be against TaskDescriptor.We need a common ground if we want to support other specs. IMHO that part of the implementation should not change now.
2. It does not matter if WDL does not support ordered maps but you need to do it in order to get same hash right?.
   If you already are using caching in production and you cannot recreate the hash, then we will need to go back to previous implementation.

**Comment by geoffjentry** [comment]
@francares At the moment cromwell is purely WDL. While we all agree that that likely won't be the case in the future it _is_ the case at this moment. Changing things for future support of non-WDL is orthogonal to changing Cromwell to support multiple backends and does not belong in these changes.

**Comment by francares** [comment]
@geoffjentry I understand you want to go back with previous part of the implementation to calculate hashes due to production concerns. What I don't understand is why you want to move that functionality to WDL bindings since you need functionality from backend to calculate the hash from content of files, etc... I think that functionality should remain in cromwell-backend.
In the current implementation you have in production, this functionality is in the engine right?
So what I'm trying to do is to keep that in Cromwell-backend since it does not hurt anyone and it does help on the design.
Please, let me know what I'm missing here.
